slice_name: Quarterly Sales
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: order_date
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: null
  dashboards:
  - 9
  datasource: 21__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby:
  - status
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: SUM
    column:
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 917
      is_dttm: false
      optionName: _col_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(Sales)
    optionName: metric_tjn8bh6y44_7o4etwsqhal
    sqlExpression: null
  only_total: true
  orientation: vertical
  rich_tooltip: true
  rolling_type: null
  row_limit: 10000
  showTooltipTotal: true
  show_empty_columns: true
  show_legend: true
  slice_id: 118
  sort_series_type: sum
  stack: Stack
  time_compare: null
  time_grain_sqla: P3M
  time_shift_color: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis: order_date
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: null
  y_axis_title_margin: 15
  y_axis_title_position: Left
query_context: '{"datasource":{"id":3,"type":"table"},"force":false,"queries":[{"filters":[{"col":"order_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P3M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P3M","columnType":"BASE_AXIS","sqlExpression":"order_date","label":"order_date","expressionType":"SQL","isColumnReference":true},"status"],"metrics":[{"aggregate":"SUM","column":{"column_name":"sales","description":null,"expression":null,"filterable":true,"groupby":true,"id":917,"is_dttm":false,"optionName":"_col_Sales","python_date_format":null,"type":"DOUBLE
  PRECISION","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"SUM(Sales)","optionName":"metric_tjn8bh6y44_7o4etwsqhal","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"column_name":"sales","description":null,"expression":null,"filterable":true,"groupby":true,"id":917,"is_dttm":false,"optionName":"_col_Sales","python_date_format":null,"type":"DOUBLE
  PRECISION","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"SUM(Sales)","optionName":"metric_tjn8bh6y44_7o4etwsqhal","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["status"],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["order_date"],"columns":["status"],"aggregates":{"SUM(Sales)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"SUM(Sales)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"order_date"}],"annotation_layers":[],"color_scheme":"supersetColors","comparison_type":null,"dashboards":[9],"datasource":"3__table","extra_form_data":{},"forecastInterval":0.8,"forecastPeriods":10,"groupby":["status"],"legendOrientation":"top","legendType":"scroll","metrics":[{"aggregate":"SUM","column":{"column_name":"sales","description":null,"expression":null,"filterable":true,"groupby":true,"id":917,"is_dttm":false,"optionName":"_col_Sales","python_date_format":null,"type":"DOUBLE
  PRECISION","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"SUM(Sales)","optionName":"metric_tjn8bh6y44_7o4etwsqhal","sqlExpression":null}],"only_total":true,"orientation":"vertical","rich_tooltip":true,"rolling_type":null,"row_limit":10000,"showTooltipTotal":true,"show_empty_columns":true,"show_legend":true,"slice_id":87,"sort_series_type":"sum","stack":"Stack","time_compare":null,"time_grain_sqla":"P3M","time_shift_color":true,"tooltipTimeFormat":"smart_date","truncateXAxis":true,"truncate_metric":true,"viz_type":"echarts_timeseries_bar","x_axis":"order_date","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"x_axis_time_format":"smart_date","x_axis_title_margin":15,"y_axis_bounds":[null,null],"y_axis_format":null,"y_axis_title_margin":15,"y_axis_title_position":"Left","force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 692aca26-a526-85db-c94c-411c91cc1077
version: 1.0.0
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
