[project]
name = "multiagent1"
version = "0.1.0"
description = "multiagent1 using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.5a2"
]

[project.scripts]
multiagent1 = "multiagent1.main:run"
run_crew = "multiagent1.main:run"
train = "multiagent1.main:train"
replay = "multiagent1.main:replay"
test = "multiagent1.main:test"
run_with_trigger = "multiagent1.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
